[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_files = [
    "_version.py:__version__"
]
version_provider = "commitizen"
version_scheme = "semver"
version = "0.8.1"
update_changelog_on_bump = true
major_version_zero = true