[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_files = [
    "_version.py:__version__"
]
version_scheme = "semver"
version = "0.0.2"
update_changelog_on_bump = true
